version = 0.1
[default.deploy.parameters]
stack_name = "call-insight-foundation-stack"
resolve_s3 = true
s3_prefix = "call-insight-foundation-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []
